version: 2
sources:
  - name: movie_rentals
    schema: public
    quoting:
      database: false
      schema: false
      identifier: false
    loader: stitch
    tables:
      - name: staff
      - name: address
      - name: city
      - name: store
      - name: film
      - name: film_actor
      - name: actor
      - name: language
      - name: country
      - name: customer